PreCommit:
  BundleCheck:
    enabled: true

  HardTabs:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    include:
      - '**/*.gemspec'
      - '**/*.rb'
      - '**/Gemfile'
      - template-dir/hooks/overcommit-hook

  TravisLint:
    enabled: true
    command: ['bundle', 'exec', 'travis']
    flags: ['lint', '--skip-version-check']

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
